# Hello Django

## 27.9.2024

## a) Esimerkkiohjelma Djangolla

> Klo 18:52, tuotantoympäristön asennuksen aloitus

Aloitin tehtävien teon käynnistämällä virtuaalikoneeni ja ajamalla siellä terminaalissa tutun komennon `sudo apt-get update`. Päivitysten jälkeen otin yhteyden virtuaalipalvelimeeni komennolla `ssh erikak@165.232.86.216`, ja ajoin myös siellä päivityskomennon.

Lähdin etenemään Tero Karvisen ohjeen mukaan (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/), ja ensimmäisenä asensin virtuaalipalvelimelleni virtualenvin, joka on siis työkalu jolla voidaan luoda eristettyjä Python ympäristöjä (lähde: Virtualenv, https://virtualenv.pypa.io/en/stable/).

Asennus tehtiin komennolla `sudo apt-get -y install virtualenv`. Seuraavaksi ajoin komennon `virtualenv --system-site-packages -p python3 env/`, joka luo kansion **/env**. Kansion kautta voidaan käyttää paketteja virutaalisten ympäristöjen ulkopuolellakin, sillä Pythonin paketteja voi asentaa myös komennolla apt-get komennolla. (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/)

Kävin kurkkaamassa, mihin kansio sijoittautui ja mitä se piti sisällään. Ilmeisesti ohjeessa mainittu lib/site-packages/ -kansio muodostuu myöhemmin, sillä sitä en listauksesta löytänyt.

![image](https://github.com/user-attachments/assets/2ec378f0-aae3-47ad-8100-79df5edfb468)

Seuraavaksi käytin uutta virtuaalista ympäristöä komennolla `source env/bin/activate`. Komento ei ensiyrittämällä onnistunut, sillä olin env/ kansion sisässä, mutta kotikansiossa ollessani komento antoi Teron ohjeen mukaisen (env) -alun terminaaliin. 

![image](https://github.com/user-attachments/assets/c0448de6-7c6a-4648-861b-abd1dfc71d79)

Seuraavaksi tarkistin, että olin varmasti virtuaaliympäristön sisällä, komennolla `which pip`.

![image](https://github.com/user-attachments/assets/19f056b6-562b-4361-b324-c83b03578bf5)

Tarkistuksen jälkeen asensin micron, joka olikin jo asennettuna virtuaalipalvelimeen, eli näemmä myös virtuaaliympäristöön. Sen jälkeen loin microlla uuden tekstitiedoston nimeltä requirements.txt, johon kirjoitin sisään **django**. Tallensin tiedoston painamalla Ctrl+S, ja poistun editorista painamalla Ctrl+Q. Tulostin terminaaliin vielä tiedoston sisällön, Teron ohjeen mukaisesti.

![image](https://github.com/user-attachments/assets/063f60d9-e2e1-46f9-b6a7-21e5e68b2273)

Seuraavaksi asensin Djangon, ja tarkistin asennnuksen jälkeen, mikä versio Djangosta on käytössä. (Yhden typon kautta, kuinkas muutenkaan...)

![image](https://github.com/user-attachments/assets/fce68683-ec33-403b-97e2-e060cc7ddc1e)

> Klo 19:17, tuotantoympäristö asennettuna, kahvinkeittotauko

> Klo 19:40, projektin luonnin aloitus

Teron ohjeen mukaan loin uuden projektin komennolla `django-admin startproject erikako`, ja lähdin kokeilemaan sitä. Ohjeesta poiketen sain virheilmoituksen, jonka mukaan minulla on 18 "unapplied migrations". Googlettelun jälkeen löysin Mediumin artikkelin aiheesta, jossa otettiin kantaa virheiden käsittelyyn (lähde: Taylor Berukoff, https://medium.com/@taylorberukoff/your-essential-django-setup-checklist-from-virtualenv-to-runserver-2fd8896e560c), mutta Teron ohjetta selatessani eteenpäin huomasin, että myös siellä otetaan kantaa näihin virheisiin vähän samalla tavalla kuin Mediumin artikkelissa, joten päätin tässä vaiheessa jättää virheet huomiotta.

![image](https://github.com/user-attachments/assets/cf9e3bcf-ac23-42df-a35f-b1171f51b441)

Testasin vielä selaimessa, että IP-osoite toimii, ja sain virheilmoituksen "Unable to connect".

![image](https://github.com/user-attachments/assets/4ed1ad84-f1e1-4825-81e8-3c6bc12dd718)

Kokeilin, toimisiko sivu jos lopetan käynnistetyn serverin terminaalissa komennolla Ctrl+C, ja käynnistän sen uudestaan, mutta sama lopputulos, eli samat herjat terminaalissa, eikä nettiselain näytä sivustoa. Nopean googlettelun tuloksena löysin keskustelun samaisesta ongelmasta, ja siellä oli vastattu, että onhan palvelimen palomuurissa reikä portille 8000 (lähde: Django, https://forum.djangoproject.com/t/cant-access-django-server-from-browser/22216). Tätä epäilin itsekin, ja halusin tietää, mitkä portit aiemmin olin aiemmin aukaissut. Etsin netistä tietoa, miten saan tietooni helposti ne portit, jotka on auki, mutta muutamia eri artikkeleita selatessani en löytänyt mielestäni tarpeeksi yksinkertaista ja nopeaa tapaa selvittää asiaa. Luotin siis omiin muistiinpanoihini, ja kävin tarkistamassa tehtävän h4 (https://github.com/koskinene/linux-course/blob/main/h4.md), mitkä portit olin avannut virtuaalipalvelimelle.

Avasin uuden terminaalin, jossa otin uuden yhteyden virtuaalipalvelimelle. Tässä kohtaa etsin tietoa, meneekö portin 8000 avaaminen samalla tavalla kuin porttien 80 ja 22 avaukset, ja löysinkin StackOverflown keskustelun (lähde: https://stackoverflow.com/questions/61561295/port-8000-not-enable-even-after-enable-it-on-firewall-ubuntu-18), jossa oli kerrottu suhteellisen yksinkertainen tapa listata avoinna olevat portit komennolla `sudo ufw status`, joten ajoin vielä sen varmistaakseni portit.

![image](https://github.com/user-attachments/assets/e6daad7a-a9b9-43b0-8f64-78e613c7c7e5)

Avasin palomuuriin reiän portilla 8000 komennolla `sudo ufw allow 8000/tcp`, ja tarkistin, että tulihan portti avoinna olevien listaukseen.

![image](https://github.com/user-attachments/assets/4c3d2be8-f157-499d-89cd-ff683e1b33ed)

Poistuin virtuaalikoneelta toisessa terminaalissa komennolla "exit", ja suljin terminaali-ikkunan. Jatkoin toisessa terminaali-ikkunassa, jossa ensin lopetin serverin pyörimisen komennolla Ctrl+C, ja käynnistin sen taas uudestaan. Vieläkään ei selaimessa näkynyt muuta kuin sama virheilmoitus, ja ajattelin kokeilla poistumista virtuaaliympäristöstä kokonaan, ja kokeilemalla uudestaan alusta.

Löysin StackOverflown keskustelun (lähde: StackOverflow, https://stackoverflow.com/questions/990754/how-to-leave-exit-deactivate-a-python-virtualenv), jossa kerrottiin kuinka virtuaaliympäristöstä pääsee pois, ja ajoin komennon `deactivate`, ja ainakin (env) -alku poistui terminaalista. Poistuin virtuaalipalvelimelta komennolla "exit", ja suljin varuilta vielä koko terminaali-ikkunankin.

> Klo 20:20, uusi yritys

Avasin uuden yhteyden virtuaalipalvelimelle, aktivoin uudelleen yhteyden virtuaaliympäristöön ja siirryin oikeaan projektikansioon. 

![image](https://github.com/user-attachments/assets/859615bd-a7ff-4df8-a06c-b95c949146e3)

Ajoin komennon `./manage.py runserver`, samat virheilmoitukset terminaalissa, eikä selaimessa edelleenkään näy muuta kuin virheilmoitus.

Googlettelulla en löytänyt oikein mitään järkevää, joten kysyin ChatGPT:ltä apua.

![image](https://github.com/user-attachments/assets/a6514ec8-3dbd-461b-8729-5cbda430bc38)

![image](https://github.com/user-attachments/assets/6f3beec7-3b35-4d10-bf2d-76b00b2bdf8e)

Lähdin kokeilemaan näillä ohjeilla, joten ensin stoppasin serverin painamalla Ctlr+C. Seuraavaksi käynnistin sen komennolla `./manage.py runserver 0.0.0.0:8000`. 2. kohdan olin juuri äsken tehnyt, eli reikä palomuuriin porttia varten. 3. kohdan skippasin, koska tiedän serverini IP-osoitteen, joten kokeilin suoraan kohtaa 4.

![image](https://github.com/user-attachments/assets/43442c9d-15cb-46dc-854a-ce2bd2eafb4c)

Aloin epäilemään, pitikö tehtävä tehdä edes virtuaalipalvelimen puolella, sillä tietysti nettiselain on virtuaalikoneen puolella, kun taas djangon asennukset yms. on tehty virtuaaliserverille, eikä siksi tietysti IP-osoite toimikaan virtuaalikoneen puolella. Tehtävänannossa sanotaan että voi halutessaan käyttää "testipalvelinta", ja seuraava tehtäväkin ohjeistetaan tekemään virtuaalikoneen puolella.

Aloitetaan siis alusta. Stoppasin serverin virtuaalipalvelimen puolella, ja vaihdoin terminaalissa takaisin oman virtuaalikoneeni puolelle. 

> Klo 20:55, uudestaan aloitus pienen hengitystauon jälkeen

Asensin tuotantoympäristön komennolla `sudo apt-get -y install virtualenv`, loin env/ -kansion komennolla `virtualenv --system-site-packages -p python3 env/` ja aktivoin virtuaaliympäristön komennolla `source env/bin/activate`. 

Etenin Teron ohjeen mukaisesti komennoilla, ja tässä kohtaa kaikki meni kuten aiemminkin virtuaaliserverin puolella.

![image](https://github.com/user-attachments/assets/cd8a6b9c-e034-4f31-9e87-c352daab1873)

Seuraavaksi loin projektin samaan tapaan kuin aiemminkin, komennolla `django-admin startproject erikako`, siirryin kansioon komennolla `cd erikako`, ja ajoin siellä komennon `./manage.py runserver`. Samat herjat terminaalissa unapplied migrations, mutta viimein selain toimii!

![image](https://github.com/user-attachments/assets/435a8604-2a4e-4870-87bf-cb8a92ad60eb)

Käyttöönotto oli huomattavasti nopeampaa näin toisen kerran tehtynä... 

Seuraavaksi jatkoin ohjeen mukaan adminin käyttöliittymän luontiin. Nettiselain näytti ihan oikein kirjautumisikkunaa, ja terminaalissa tapahtui lokitusta.

![image](https://github.com/user-attachments/assets/a88e7d20-4585-4d00-ae01-80fd0c84eb93)

Serveri oli stopattava, jotta pääsin kirjoittamaan komentoja joilla päivitetään tietokannat sekä luodaan käyttäjä.

Tietokannat päivitettiin Teron ohjeen mukaan komennoilla `./manage.py makemigrations` ja `./manage.py migrate`.

![image](https://github.com/user-attachments/assets/faaf647e-5636-4240-bebe-774ebd158091)

Lisäsin käyttäjän ohjeen mukaisilla komennoilla, ensin asensin pwgenin komennolla `sudo apt-get install pwgen`. Pwgen siis generoi salasanoja, ja käytin sitä salasanan luontiin komennolla `pwgen -s 20 1`. Otin salasanan talteen, ja loin "superuserin" komennolla `./manage.py createsuperuser`. Jätin käyttäjänimen tyhjäksi, jolloin se on erikak, en syöttänyt sähköpostia ja laitoin salasanan kahteen kertaan.

Kokeilin kirjautumista selaimessa, mutta eihän se toiminut koska serveri ei ollut päällä. Käynnistin sen uudestaan terminaalissa käyttäen komentoa `./manage.py runserver`.

Nyt terminaalissa ei näkynyt enää varoituksia, ja pääsin selaimen kautta kirjautumaan.

![image](https://github.com/user-attachments/assets/a996da31-06ca-4e36-8030-fdca1e69fd6c)

Ohjeessa jää epäselväksi, pitääkö uusi käyttäjä luoda terminaalin vai nettiselaimen kautta, mutta päätin ensin kokeilla käyttäjän luontia nettiselaimen kautta. Tämä tehtiin valitsemalla vasemman reunan Users -kohdasta "Add", ja lisäämällä käyttäjälle käyttäjänimi sekä salasana. Painoin alareunasta "Save and continue editing", jotta pääsisin lisäämään käyttöoikeuksia käyttäjälle. Alempana sivulta löytyi kohta "Permissions", jossa rastin kohdat "Staff status" sekä "Superuser status". 

![image](https://github.com/user-attachments/assets/e00e260f-d800-4523-9fe0-a99b4a490177)

En tehnyt käyttäjään muita muutoksia, ja tallensin tehdyt muutokset alareunan "SAVE"-nappia painamalla, jolloin sivu kertoi "The user "testailu" was changed successfully", eli kaikki OK. Seuraavaksi kirjauduin ulos, ja kirjauduin sisään juuri luomallani käyttäjällä ja kaikki näyttäisi toimivan kuten pitääkin.

![image](https://github.com/user-attachments/assets/4768a98a-d1e1-414c-8545-b5cfc9ce34c3)

Testasin vielä testailu-käyttäjän oikeudet luomalla yhden uuden käyttäjän, jolle en laittanut mitään oikeuksia. Käyttäjän luominen onnistui ongelmitta, eli oikeudet juuri luodulle testailu-käyttäjälle olivat kunnossa. Users -listaa katsomalla näin, että myös Staff -statuksen kohdalla on vihreä merkintä testailu-tunnuksen kohdalla, eli myös se oikeus oli kunnossa.

> Klo 21:28, asiakastietokannan luonnin aloitus

Aloitin tietokannan luonnin Teron ohjeen mukaan komennolla `./manage.py startapp crm`, joka luo uuden kansion Customer Relationship Management (CRM) -sovellukselle (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/). Lisäsin microlla crm -sovelluksen settins.py -tiedostoon kohtaan INSTALLED_APPS, tallensin painamalla Ctrl+S ja poistuin microsta painamalla Ctrl+Q.

Seuraavaksi ohjeen mukaisesti lisäsin mallin komennolla `micro crm/models.py`. Customer -luokka lisää näillä määrityksillä customer -taulun tietokantaan, ja lisää tauluun name -sarakkeen. Taas tallennus Ctlr+S ja poistuminen Ctrl+Q.

![image](https://github.com/user-attachments/assets/adf547a3-ec70-4109-9b78-7dbaf7cf5306)

Seuraavaksi ajoin komennot migraatioita varten, eli otin äsken tehdyn mallin "käyttöön".

![image](https://github.com/user-attachments/assets/396c9fed-8511-4f77-8967-83b851d0adbf)

Rekisteröin ohjeen mukaisesti juuri luodun tietokannan näkymään adminille muokkaamalla microlla tiedostoa admin.py. Ctrl+S tallennukseen ja Ctrl+Q poistumiseen. 

![image](https://github.com/user-attachments/assets/9a77a08c-e5e0-4dd7-8009-ca72ff471369)

Laitoin serverin käyntiin komennolla `./manage.py runserver`, ja kirjauduin admin-näkymästä sisään. Juuri luotu Customers -tietokanta näkyi. Testasin tietokannan toimintaa lisäämällä kaksi käyttäjää, poistamalla yhden, lisäämällä yhden ja muokkaamalla toista. Kaikki toiminnot toimivat normaalisti.

![image](https://github.com/user-attachments/assets/c56f886c-8aab-495f-a4fd-b78c02ff0df9)

Seuraavaksi aloin ohjeen mukaan muokkaamaan models.py -tiedostoa, jotta saisin admin-näkymään tietokannan asiakkaat listattua nimillä. Stoppasin serverin Ctrl+C, ja pääsin muokkaamaan tiedostoa komennolla `micro crm/models.py`. Lisäsin rivit 6 ja 7.

![image](https://github.com/user-attachments/assets/512784e3-b303-46dd-bf5e-9668b0227ca7)

Testasin toimintaa vielä selaimen puolella, ja nyt listauksessa on nätisti asiakkaiden nimet näkyvillä.

![image](https://github.com/user-attachments/assets/772409c4-8867-4e4b-af8e-a1905cee84d4)

> Klo 21:51, tehtävä purkissa, hieman harmittaa taas alun säätäminen ja ajan"tuhlaus"

Jatkoin vielä samaan putkeen, ja kävin sulkemassa aiemmin avaamani portin 8000 virtuaalipalvelimellani löytämäni ohjeen mukaisesti (lähde: E2E Networks Limited, https://docs.e2enetworks.com/guides/ufw.html).

![image](https://github.com/user-attachments/assets/4e0c5c54-2df6-41d9-9dad-40cfda9c8c48)

> Klo 21:56, pienen tauon paikka

## b) Djangon tuotantotyyppinen asennus

> Klo 22:17

Luin ensin Tero Karvisen ohjeen läpi (lähde: Tero Karvinen, https://terokarvinen.com/2022/deploy-django/). 

Pystyin skippaamaan ohjeen alkuosion, sillä virtuaalikoneellani on jo micro sekä apache2 asennettuna. Aloitin kohdasta "Create some web content as a user". Lisäsin kansion, ja muokkasin sen index.html -tiedostoa echo -komennon kautta.

![image](https://github.com/user-attachments/assets/c9664c21-7433-45a3-8236-ab608df0c679)

Lisäsin uuden VirtualHostin sudoeditin avulla, komennolla `sudoedit /etc/apache2/sites-available/koskinene.conf` pääsin muokkaamaan tiedostoa microssa. Määritin sinne oikeat tiedot, tallensin Ctrl+S ja poistuin editorista Ctrl+Q. 

![image](https://github.com/user-attachments/assets/c79b2767-770b-4e38-8f36-fe815a2c8e57)

Otin uuden sivun käyttöön ja disabloin vanhan. 

![image](https://github.com/user-attachments/assets/cafcf9d0-4893-4a2b-9f1e-8c1f203e2908)

Testasin tehtyjä konfiguraatioita ennen apachen "potkaisua". Ohjeen mukaan configtest saa "valittaa" julkisesta nimestä, mutta jos "Syntax OK", on konfiguraatiot kunnossa.

![image](https://github.com/user-attachments/assets/7fcdef12-8fc1-4207-aafa-fb952309e976)

Seuraavaksi potkaisin apachen uudelleen käyntiin komennolla `sudo systemctl restart apache2`. Testasin toimintaa curlilla, mutta oikeaa sivua ei löytynyt. 

![image](https://github.com/user-attachments/assets/033f251f-42b9-42d9-ba90-4f8914fa97a0)

Uskoin ongelman johtuvan siitä, että virtuaalikoneella on localhostiin tehty jo jonkinlainen sivu näkyviin, joten päätin testata curlilla pelkän localhostin toimintaa, ja siellähän näkyi tehtävässä h3 luotu hattu.example.com -sivu. 

![image](https://github.com/user-attachments/assets/46a45fb0-289a-45a2-8a20-bc31dbf7d682)

Kävin kurkkaamassa, mitä kaikkia tiedostoja /etc/apache2/sites-available -kansiossa oikein olikaan, ja disabloin hattu.example.com.conf -tiedoston. 

![image](https://github.com/user-attachments/assets/1d26e3b0-25b4-4db5-8cae-0cedf1937cec)

Tein uudestaan demonin potkaisun komennolla `sudo systemctl restart apache2`, ja kokeilin curlilla uudestaan http://localhost/static/ -sivun toimintaa, ja nyt näytti oikealta.

![image](https://github.com/user-attachments/assets/b4f67700-bcc9-4ae2-a6c4-63d651b97d7a)

> Klo 22:42, uuden Django-projektin luonti

Skippasin Teron ohjeesta VirtualEnvin ja Djangon asennukset, sillä ne on tehty jo ensimmäisessä tehtävässä. Jatkoin uuden Django-projektin luomisella kohdan "New Django Project" -ohjeilla.

Vaihdoin virtualenvin puolelle komennolla `source env/bin/activate`. Loin uuden projektin nimeltä "koskinene" komennolla `django-admin startproject koskinene`. 

Muokkasin ohjeen mukaan koskinene.conf -tiedostoa ajamalla komennon `sudoedit /etc/apache2/sites-available/koskinene.conf`. Tein ohjeen mukaiset muutokset tiedostoon, välissä tarkistin Pythonin version ajamalla terminaalissa komennon `python -V`.

![image](https://github.com/user-attachments/assets/f1db4c35-ae03-40f7-b7a4-9398f383ca7b)

Seuraavaksi asensin Apachen WSGI-moduulin ohjeiden mukaisesti komennolla `sudo apt-get -y install libapache2-mod-wsgi-py3`. Testasin konfiguraatioita, näytti samalta kuin aiemminkin, eli oletin kaiken olevan kunnossa.

![image](https://github.com/user-attachments/assets/4636bb30-d91a-4d4d-a4d9-030a5334a45e)

Seuraavaksi otin muutokset käyttöön potkaisemalla Apachen uudelleen käyntiin komennolla `sudo systemctl restart apache2`, ja testasin, mitä ohjeessa ollut curl -komento näytti. 403 Forbidden, ei hyvältä vaikuttanut.

![image](https://github.com/user-attachments/assets/4d1900e2-af66-4854-98df-54fcc3682473)

Menin uudestaan katsomaan, olenhan tehnyt tarvittavat muutokset koskinene.conf -tiedostoon, sillä kopioin pohjan Teron ohjeesta. En huomannut siinä virheitä, joten kävin katsomassa vielä kansiorakenteita. Jostain syystä koskinene -kansioni on luotu suoraan /home/erikak/ -kansioon, eikä publicwsgi-kansion sisään. Kansiosta löytyykin wsgi.py -tiedosto, jonka polku piti conf-tiedostoon määritellä.

![image](https://github.com/user-attachments/assets/3dd402cd-2e6a-41bc-b9a8-75907afae318)

Olin ilmeisesti väärässä kansiossa ajaessani komennon `django-admin startproject koskinene`, ja siksi luotu projekti on /home/erikak/ -kansiossa, eikä publicwsgi-kansion sisässä. Ohjetta lukiessani huomaan, että olisin voinut käyttää ensimmäisessä tehtävässä luotua projektia, mutta koska olin hätäinen, loin uuden projektin. Mietin hetken, kannattaisiko minun poistaa luotu projekti, ja tehdä se oikeaan kansioon, vai jatkaa "väärään" paikkaan luodun projektin kanssa. Päätin nopean googlettelun seurauksena poistaa luodun projektin, ja luoda sen uudestaan oikeaan paikkaan, sillä en ole päässyt konfiguraatioissa vielä kovin pitkälle.

![image](https://github.com/user-attachments/assets/201baa90-8d5b-4e8e-82ee-6ebbeb779d73)

Peruutin ohjeessa, ja aloitin projektin luomisen uudelleen, mutta tällä kertaa oikeassa kansiossa. 

![image](https://github.com/user-attachments/assets/6c260aa1-cad2-46d6-ab8f-1da2ec0aa8e4)

> Klo 23:25, pieni tauko

> Klo 23:41, jatketaan

Tarkistin muutoksen jälkeen, täsmääkö koskinene.conf -tiedoston polut nyt oikeaa. Avasin toisen terminaali-ikkunan, jotta voin samalla pitää auki tiedostoa ja tarkistaa oikeat polut. Jotain tein silti projektin luonnissa väärin, sillä nyt wsgi.py -tiedosto löytyy rakenteella /publicwsgi/koskinene/koskinene/koskinene. Annoin sen olla, mutta korjasin määrittelyt .conf-tiedostoon. 

![image](https://github.com/user-attachments/assets/515fbbe5-2d39-4e76-801d-cb4b68c3e5b2)

Tein muutoksen testauksen ajamalla komennon `/sbin/apache2ctl configtest`. Se näyttää edelleen ihan OK:lta, joten käynnistin apachen uudelleen komennolla `sudo systemctl restart apache2`.

Testasin uudestaan, mitä komento `curl -s localhost|grep title` kertoo, ja täytyy sanoa että vastaus ei tässä kohtaa yllättänyt. 

![image](https://github.com/user-attachments/assets/ed5eb37f-d11c-4edd-86ef-b07d9cc4e857)

Uskon että projektin poisto pisti kaiken sekaisin. Pistin silti poistaen uudenkin projektin, ja yritin luoda sen tällä kertaa oikeaan kansioon. Menin siis kansioon /publicwsgi/koskinene, ja poistin siellä olleen koskinene -kansion komennolla `rm -r koskinene`.

![image](https://github.com/user-attachments/assets/59255ff4-e150-405b-b68a-bcee3813a01c)

Suljin terminaalin, vaikka en usko että sillä on juuri merkitystä. Aloitin uudestaan projektin luomisen. Tajusin raporttiani läpi lukiessani, että olin mennyt projektin luomisen hätäisesti, sillä terminaali herjasi jossain kohtaa että koskinene -kansio löytyy jo, sillä sen olen luonut mkdir-komennolla alussa, mutta tästä en tajunnut ottaa ruutukaappauksia kun luulin vaan itse säheltäväni jotain.

Otin yhteyden virtuaaliympäristöön komennolla `source env/bin/activate`, ja päätin luoda publicwsgi -kansioon ihan erinimisen projektin kuin koskinene. Siirryin siis publicwsgi -kansioon, ja ajoin siellä uudestaan projektin luomiseen tarkoitetun komennon.

![image](https://github.com/user-attachments/assets/26f9f967-d1f0-41da-8974-8739adb86c21)

Seuraavaksi avasin sudoeditillä koskinene.conf -tiedoston (ja mietin samalla, vaikuttaako tuo nimi nyt jotain asiaan, ja pitääkö se vaihtaa, mutta en tehnyt muutosta tässä kohtaa). Muokkasin sinne oikeat polut, tarkistin ne toisessa terminaali-ikkunassa, jotta varmasti menevät oikein.

![image](https://github.com/user-attachments/assets/d4fb906d-bc54-4906-88c6-e375e435de0a)

Ajoin vielä varuilta tiedoston tallentamisen jälkeen terminaalissa komennon `sudo apt-get -y install libapache2-mod-wsgi-py3`, jota en viimeksi uutta projektia luodessani muistanut tehdä, mutta joka ei selkeästi tehnyt muutoksia.

![image](https://github.com/user-attachments/assets/b7c1bfea-8860-4714-830a-593c544b0373)

Testasin konfiguraatiot komennolla `/sbin/apache2ctl configtest`, ja kaikki näyttää hyvältä. Herjaa AH00558, mutta kertoo että syntaksi on OK. Käynnistin apachen uudelleen komennolla `sudo systemctl restart apache2`. Testasin curlia uudemman kerran, mutta edelleen herjasi "500 Internal Server Error".

Ajattelin, että josko .conf-tiedoston nimi on "väärin", kun projektin nimi on nyt erika, eikä enää koskinene. Poistuin virtuaaliympäristöstä komennolla "deactivate", siirryin terminaalissa /etc/apache2/sites-available/ -kansioon, ja muokkasin tiedoston nimen komennolla `sudo mv koskinene.conf erika.conf` (lähde: Tero Karvinen, https://terokarvinen.com/2009/command-line-basics-4/), ja tarkistin komennolla `cat erika.conf`, että tiedosto on sisällöltään oikea.

Uudestaan virtuaaliympäristöön komennolla `source env/bin/activate`. Testasin syntaksin komennolla `/sbin/apache2ctl configtest`, mutta se näyttää edelleen samaa, eli sen puolesta ongelmaa ei pitäisi olla. Käynnistin apachen taas uudestaan, ja kokeilin curlia toivomatta enää mitään, mutta sentään "500 Internal Server Error" oli vaihtunut.

![image](https://github.com/user-attachments/assets/f2442326-3a15-4fbb-839b-02543f97844e)

Title ei ollut kuitenkaan se, mitä ohjeessa sanotaan, joten testaan curlilla vielä localhostin toimintaa, ja esiin tulee jokin vanha oletussivu, jonka olen todennäköisesti joskus aiemmin luonut. 

![image](https://github.com/user-attachments/assets/20e40a30-733b-4adc-b472-64463b9d5ee8)

Arvelin ongelman johtuvan nyt .conf -tiedostoista, ja ajoin toisessa terminaalissa komennon `sudo a2ensite erika.conf`. Palasin takaisin terminaaliin, jossa olen virtuaaliympäristössä, ja käynnistin apachen uudestaan.

Testasin curlia, ja taas palattiin "500 Internal Server Error" herjan pariin.

![image](https://github.com/user-attachments/assets/96550f88-7ae4-460e-9184-85c04408b77d)

Menin toisen terminaalin kautta katsomaan, mitä sivuja polussa /etc/apache2/sites-available on, ja ajoin jokaisen tiedoston komennolla `sudo a2dissite tiedostonnimi.conf`. Poistuin toisessa terminaalissa virtuaaliympäristöstä "deactivate" -komennolla, ja suljin sen kokonaan. Käynnistin Apachen uudestaan, ja ajoin sen jälkeen komennon `sudo a2ensite erika.conf`, ja taas apachen käynnistys. Epätoivoisena suljin tämänkin terminaalin, ja avasin ihan uuden ikkunan. Testasin curlia vielä uudestaan sekä virtuaaliympäristön kautta että ilman sitä, mutta ei muutosta virheilmoitukseen.

![image](https://github.com/user-attachments/assets/725903de-aa4a-46c3-a2b8-e18cedeb3c40)

Lähdin seuraavaksi tekemään asioita takaisin päin, eli ajattelin poistaa ladatun Apachen WSGI-moduulin, muokata erika.conf -tiedoston siihen mitä se oli aiemmin, ja tehdä kaiken uudestaan. Jos se ei toimi, en enää tiedä mitä tehdä mutta jääpähän tunnille ihmeteltävää.

Poistin moduulin asennuksen komennolla `sudo apt-get remove libapache2-mod-wsgi-py3`. Muokkasin sudoeditillä erika.conf -tiedostoon aiemmin luodun static -kansion tiedot. Käynnistin apachen uudelleen, pitäisi varmaan tehdä jo laskuria montako kertaa sitä on tänään potkaistu. Testasin tässä kohtaa aiemmin toiminutta `curl http://localhost/static`-komentoa, mutta vastauksena "404 Not Found", ja localhostista vastasi edelleen joku kummallinen sivu.

![image](https://github.com/user-attachments/assets/142733d9-9334-4a91-869d-018df67037c8)

Löysin sivun /var/www/html/ -kansiosta.

Aloitin tehtävän teon uudestaan alusta, ja päätin jättää jo luodut koskinene ja erika -kansiot ja tiedostot rauhaan.

> Klo 00:45, väliaikatiedoksi

Aloitin luomalla uuden kansion publicwsgi -kansioon, ja tekemällä sinne index.html -sivun.

![image](https://github.com/user-attachments/assets/0deea3d3-c445-48dc-a235-ac088ed37f52)

Seuraavaksi jatkoin uuden VirtualHostin lisäämiseen, otin uuden tarmo.conf -tiedoston käyttöön ja disabloin erika.conf -tiedoston, tarkistin konfiguraatiot, uudelleenkäynnistin apachen ja testasin static-sivun toiminnan, kaikki OK.

![image](https://github.com/user-attachments/assets/405a98b5-7609-4a4c-91c5-b2d3f91cc047)

En uskaltanut skipata ohjeesta enää mitään, ja eteenpäin lukiessani teki mieli hakata päätä seinään, sillä olin aiemmin ohittanut täysin komennon `virtualenv -p python3 --system-site-packages env`, joka luo publicwsgi -kansioon uuden virtuaalisen ympäristön. Toivoin, että tämä vaihe aiheutti aiemmat ongelmat, mutta jatkoin ohjeen mukaan eteenpäin.

Ajattelin, että kyllähän Django on jo asennettuna, mutta ei tietenkään tässä virtuaaliympäristössä, eli ei muuta kun uudestaan Djangon asennus Teron ohjeiden mukaan.

![image](https://github.com/user-attachments/assets/16e3c9be-72fc-4480-8942-ec6cf075bab8)

Seuraavaksi aloitin uuden projektin luomisen, ja tässä kohtaa huomaan saman virheen minkä ohitin aiemmin. Static-harjoituksessa on jo luotu kansio samalla nimellä, jolla yritin projektia luoda.

![image](https://github.com/user-attachments/assets/a1fdef1a-886f-4547-a294-f76d2791d8d4)

Loin uuden projektin tarmo-kansion sisään, ja kuten aiemminkin, kansiopoluksi tulee tripa-tarmo, mutta päätän silti kokeilla loppuun asti. Jos olisin luonut projektin yhtä kansiota "taaemmas", olisi kansio ollut publicwsgi -kansion ulkopuolella. 

![image](https://github.com/user-attachments/assets/49743018-1a6e-40a2-9c94-840a826df20e)

Tässä vaiheessa kyseenalaistin sitä, että menikö vieläkään oikein, koska env-kansio on publicwsgi -kansiossa, joten pitäisikö myös projektin olla samassa kansiossa? Tähän ajatukseen juuttuneena poistin luodun tarmo -kansion publicwsgi -kansiosta, ja tein uuden projektin samaan kansioon uudestaan.

![image](https://github.com/user-attachments/assets/85fd7c25-541a-4e6f-98eb-cea205904dfe)

Seuraavaksi muokkasin tarmo.conf -tiedoston vastaamaan oikeita polkuja ja konfiguraatioita. 

![image](https://github.com/user-attachments/assets/8f7a20d9-1b1a-465f-a7c1-c699e1055ab6)

Asensin Apachen WSGI-moduulin uudestaan komennolla `sudo apt-get -y install libapache2-mod-wsgi-py3`, tarkistin syntaksin ja käynnistin apachen uudestaan. Testaus, enkä ymmärrä mikä tässä taas meni pieleen.

![image](https://github.com/user-attachments/assets/221fa57e-46df-40db-b5f3-3d856288b819)

Kävin kurkkaamassa viimein, mitä apachen errorlog kertoo. 

![image](https://github.com/user-attachments/assets/115f9e62-d04f-4df5-b2ff-6e3833fe5ce2)

Kävin myös kurkkaamassa, mitä tiedoston wsgi.py rivillä 12 on, mutta en viisastunut.

![image](https://github.com/user-attachments/assets/ee89259b-1434-4836-b978-b3a58d00445a)

> Klo 1:30, ei auta kun luovuttaa ja antaa aivoille unta

## 29.9.2024

> Klo 18:44, jatketaan yrittämistä

Ajattelin, että lähestyn asiaa yrittämällä viimeksi tehtyä projektia toimintaan, ja jos se ei toimi, yritän luoda vielä yhtä uutta, ja jatkan sen kanssa vianselvitystä. Ensin siis virtuaalikone auki ja tuttu komento `sudo apt-get update`.

Kokeilin curlia niin virtuaaliympäristössä kuin sen ulkopuolella, mutta herja pysyy samana.

![image](https://github.com/user-attachments/assets/438d0ba8-2a58-47e4-aec3-19918514d1f7)

Otetaas vielä kerran alusta. Lähdin Teron ohjeen mukaan etenemään, heti Apache2 asennuksesta alkaen, vaikka se toki minulla jo löytyykin. Jotain Apachessa on kuitenkin solmussa, sillä `curl localhost` antaa saman, 500 Internal Server Error -virheilmoituksen. Kävin tarkistamassa kansion /var/www/html/ index.html-tiedoston, joka oli paikallaan ja oikean näköinen, ja uudelleen käynnistin Apachen komennolla `sudo systemctl restart apache2`, mutta virheilmoitus localhostista ei poistu. 

Googletin ongelmaa, ja jostain keskustelusta (lähde: Stack Overflow, https://stackoverflow.com/questions/40403871/curl-and-wget-return-error-500-for-helloworld-php-on-new-install-but-browser-is) näin maininnan httpd.conf -tiedostosta, ja tuli mieleeni, että olenko disabloinut liikaa tiedostoja kansiossa /etc/apache2/sites-available/, joten kävin katsomassa mitä default-ssl.conf -tiedosto pitää sisällään. Aiempien ohjeiden mukaisesti 000-default.conf -tiedosto saakin olla pois päältä, mutta tuo toinen varmastikaan ei. Otin tiedoston käyttöön komennolla `sudo a2ensite default-ssl.conf`, ja yritin uudelleen käynnistää apachea komennolla `sudo systemctl restart apache2`, mutta sain virheilmoituksen.

![image](https://github.com/user-attachments/assets/9db992a5-3347-49d5-a945-e79fc40f81cb)

Ajoin virheilmoituksessa mainitun komennon `systemctl status apache2.service`, ja näytti siltä, että apachen serveri ei ole päällä. 

![image](https://github.com/user-attachments/assets/fe8ae0f8-67b2-4058-8422-c5c1e7002668)

Ajoin vielä toisen virheilmoituksessa mainitun komennon `sudo journalctl -xeu apache2.service`.

![image](https://github.com/user-attachments/assets/71b56ff4-83a4-4e57-8a97-4c0155d4fe37)

Silmääni osui rivi "syys 29 19:03:26 ketku apachectl[3991]: AH00526: Syntax error on line 24 of /etc/apache2/sites-enabled/default-ssl.con>", eli juuri se tiedosto, minkä äsken otin käyttöön. Avasin sen microlla tarkasteluun, mutta en tullut aiheessa viisaammaksi. Selasin muutamia keskusteluja aiheesta, ja yhdessä oli neuvona Apachen uudelleenasennus (lähde: Ask Ubuntu, https://askubuntu.com/questions/629995/apache-not-able-to-restart), joka kuulosti minulle tässä vaiheessa järkevältä.

Tein poiston komennolla `sudo apt-get purge apache2`. Poisto onnistui ongelmitta, mutta koska kansiot /var/www/html/ ja /etc/apache2/sites-available/ eivät olelet tyhjiä, niitä ei terminaalin mukaan poistettu. Seuraavaksi uudelleen asennus komennolla `sudo apt-get install apache2`.

Uudelleenasennus selkeästi korjasi jotain, sillä nyt komento `curl localhost` palauttaa kansion /var/www/html/ tiedoston index.html sisällön.

> Klo 19:26, pienen tauon paikka

> Klo 19:51, jatketaan

Jatkoin Teron ohjeen mukaan, käytin jo luotua kansiota /publicwsgi/koskinene/static/, jossa jo aiemmin luotu index.html tiedosto sijaitsi. Tein sille uuden conf. -tiedoston komennolla `sudoedit /etc/apache2/sites-available/koskinene.conf` ja tein tarvittavat lisäykset.

![image](https://github.com/user-attachments/assets/0b1af416-2252-4b37-833c-5aaaa0bcd042)

Otin juuri tehdyn .conf -tiedoston käyttöön, otin 000-default.conf -tiedoston pois käytöstä, ja kokeilin configtestillä mikä tilanne. HSama herja AH00558, mutta syntaksi OK, joten seuraavaksi apachen uudelleenkäynnistys komennolla `sudo systemctl restart apache2`.

![image](https://github.com/user-attachments/assets/9ca2e99d-001d-44ce-8471-c4fb8c625a84)

Kokeilin curlilla, toimiko localhost/stacit/ -sivu, ja toimihan se.

![image](https://github.com/user-attachments/assets/ac42d736-e94c-4ae1-a173-f5e1815cd972)

Selvyyden vuoksi poistin aiemmin asennetun virtualenvin ja asensin sen uudestaan komennoilla `sudo apt-get purge virtualenv` ja `sudo apt-get -y install virtualenv`. Seuraavaksi loin uuden virtuaaliympäristön komennolla `virtualenv -p python3 --system-site-packages env`. 

Vaihdoin virtuaaliympäristön sisään komennolla `source env/bin/activate`. Tarkistin komennolla `which pip`, että onhan käytettävä pip tulossa nimenomaan env/ kansiosta.

![image](https://github.com/user-attachments/assets/a6b320c5-9c44-4807-a408-1ae6a4f07f42)

Kansiossa oli jo aiemmin luotu micro requirements.txt, joten kävin vielä tarkistamassa että siellä lukee **django**, ja kokeilin Djangon uudelleen asennusta komennolla `pip install -r requirements.txt`, ja Djangon asennus tosiaan olikin jo voimassa. Testasin vielä version.

![image](https://github.com/user-attachments/assets/6856d640-9910-4465-aa63-25a0234008f6)

Seuraavaksi ohjelmassa oli uuden Django projektin luominen, ja yritin luoda taas vahingossa saman nimistä projektia, kuin mikä minulla kansiossa jo static-osiossa oli luotuna. Tein projektin uudella nimellä.

![image](https://github.com/user-attachments/assets/5356f70a-e0f0-479a-b174-2a7829fc5644)

Tarkistin kansiorakenteen, jotta osaan määritellä sen oikein seuraavaksi muokattavaan erikako.conf -tiedostoon.

![image](https://github.com/user-attachments/assets/90de2db0-f1d7-4255-a0a9-830b1fee2d1a)

Komennolla `sudoedit /etc/apache2/sites-available/erikako.conf` pääsin muokkaamaan tiedostoa. Kopioin Teron ohjeessa olleen pohjan, mutta muutin omat kansiorakenteet käyttöön.

Tässä vaiheessa tajuan ehkä yhden virheistäni. VirtualHost -bloksissa käytetään /static/ kansiota, joka minulla on toki luotuna aiemmassa tehtävässä (/publicwsgi/koskinene/static/), mutta jota ei nyt luodussa erikako -projektissa tietenkään ole. 

![image](https://github.com/user-attachments/assets/9002a47d-f128-4e27-8a6c-739b8b0a7beb)

En osaa muuttaa VirtualHostin blokkiin oikeaa rakennetta ilman static-kansiota, joten päätin luoda static -kansion myös erikako -kansioon.

![image](https://github.com/user-attachments/assets/c6cf57e7-9736-4460-b607-aa8ac511475c)

Seuraavaksi 

















































